services:
  mysql:
    image: mysql:8.0
    container_name: do-shopping-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'do_shopping'
      MYSQL_ROOT_PASSWORD: '1234'
      TZ: 'Asia/Jakarta'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    deploy:
      resources:
        limits:
          memory: 5024M
    container_name: do-shopping-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Override data source URL dari localhost ke nama container mysql ('mysql')
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/do_shopping?useSSL=false&serverTimezone=Asia/Jakarta&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysql

volumes:
  mysql_data:
