spring.datasource.url=${DB_URL:jdbc:mysql://mysql:3306/do_shopping?useSSL=false&serverTimezone=Asia/Jakarta&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
