spring.application.name=do-shopping
spring.profiles.active=dev

# Common configurations
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jackson.time-zone=Asia/Jakarta

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Default JWT Secret (can be overridden via JWT_SECRET environment variable)
jwt.secret=${JWT_SECRET:BLA_BLA_BLA_623412123423423askdhajkshdjkhh134h23423238u2384ejfhsdfhsdfhsdlf}