CREATE TABLE categories (
  id CHAR(36) NOT NULL,
  name VARCHAR(50) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(50) NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by VARCHAR(50) NOT NULL,
  deleted_at DATETIME DEFAULT NULL,
  deleted_by VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
);