CREATE TABLE users (
  id CHAR(36) NOT NULL,
  email VARCHAR(100),
  username VARCHAR(50) NOT NULL,
  password TEXT NOT NULL,
  role ENUM('ADMIN','CUSTOMER') NOT NULL,
  is_active TINYINT DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(50) NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by VARCHAR(50) NOT NULL,
  deleted_at DATETIME,
  deleted_by VARCHAR(50),
  PRIMARY KEY (id)
);