CREATE TABLE orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customer_id INT NOT NULL,
  order_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  total_quantity INT NOT NULL,
  total_amount DECIMAL(18,2) NOT NULL,
  note TEXT,
  status ENUM('PENDING','PAID','PROCESSING','SHIPPED','COMPLETED','CANCELLED'),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(50) NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by VARCHAR(50) NOT NULL,
  deleted_at DATETIME,
  deleted_by VARCHAR(50),
  FOREIGN KEY (customer_id) REFERENCES customers(id)
);